application:
  neo4j:
    uri: ${NEO4J_URL:bolt://localhost:7687}
    username: ${NEO4J_USERNAME:neo4j}
    password: ${NEO4J_PASSWORD:neo4j}
  trello:
    boardId:  ${TRELLO_BOARD_ID:SHORT_BOARD_SHARE_ID}
    url:  ${TRELLO_URL:https://api.trello.com/1/}
    apiKey: ${TRELLO_API_KEY:aaaaaaaaaaaaaa}
    apiToken: ${TRELLO_API_TOKEN:bbbbbbbbbbbbbbbbbbbbbb}