application:
  neo4j:
    uri: ${NEO4J_URL:bolt://188.68.50.2:7687}
    username: ${NEO4J_USERNAME:neo4j}
    password: ${NEO4J_PASSWORD:JV7GlVyIg5bj}
  trello:
    boardId:  ${TRELLO_BOARD_ID:KWeHYqWo}
    url:  ${TRELLO_URL:https://api.trello.com/1/}
    apiKey: ${TRELLO_API_KEY:df1e086d197a13ded596f75b7e5a4abc}
    apiToken: ${TRELLO_API_TOKEN:9d23c87fb9e1539695c9cfebf02e025a6f342257b165af2989673dba808ffb39}